name: aceprex
description: Aceprex INC.

publish_to: 'none'


version: 3.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.4+1
  cached_network_image: ^3.2.3
  chat_bubbles: ^1.4.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  date_format: ^2.0.7
  dio: ^5.2.0+1
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_image_compress: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.10.1
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_storage: ^2.1.1
  glassmorphism: ^3.0.0
  google_fonts: ^4.0.4
  grouped_list: ^5.1.2
  http: ^0.13.6
  image_picker: ^0.8.7+5
  image_picker_ios: ^0.8.7+4
  image_picker_platform_interface: ^2.8.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  lottie: ^2.4.0
  mime: ^1.0.4
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  rxdart: ^0.27.7
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  syncfusion_flutter_pdfviewer: ^21.2.8
  time: ^2.1.3
  url_launcher: ^6.1.11
  url_strategy: ^0.2.0
  workmanager: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/animi/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
